/**
 * Manages requests for moving data between different security domains (Cross-Domain Solution).
 * This class facilitates the process of requesting data classification downgrades or upgrades,
 * emitting events that can be handled by a guard or approval workflow, and provides
 * automated sanitization and downgrading capabilities.
 */
export class CrossDomainSolution {
	/** @private @type {import('../HybridStateManager.js').default} */
	#stateManager;

	/**
	 * Creates an instance of CrossDomainSolution.
	 * @param {object} context - The application context.
	 * @param {import('../HybridStateManager.js').default} context.stateManager - The main state manager instance.
	 */
	constructor({ stateManager }) {
		if (!stateManager) {
			throw new Error("[CrossDomainSolution] StateManager is required.");
		}
		this.#stateManager = stateManager;
	}

	/**
	 * Initiates a request to downgrade the classification of a data entity.
	 * This is typically used when data needs to be moved from a higher security level to a lower one.
	 * The request is emitted as a 'cdsEvent' for an external guard or workflow to process.
	 *
	 * @param {object} params - The parameters for the downgrade request.
	 * @param {string} params.dataId - The unique identifier of the data entity to be downgraded.
	 * @param {string} params.fromLevel - The current security classification level of the data.
	 * @param {string} params.toLevel - The target (lower) security classification level.
	 * @param {string} params.justification - The reason or justification for the downgrade request.
	 * @returns {Promise<{ticketId: string, status: string}>} A promise that resolves with an object containing the ticket ID for tracking the request and its initial status.
	 */
	async requestDowngrade({ dataId, fromLevel, toLevel, justification }) {
		this.#stateManager?.emit("cdsEvent", {
			type: "request_downgrade",
			dataId,
			fromLevel,
			toLevel,
			justification,
			ts: Date.now(),
		});
		return { ticketId: crypto.randomUUID(), status: "pending" };
	}

	/**
	 * Initiates a request to upgrade the classification of a data entity.
	 * This is used when data from a lower security level is incorporated into a higher-level entity,
	 * requiring a formal process to approve the data's new classification.
	 * The request is emitted as a 'cdsEvent' for an external guard or workflow to process.
	 *
	 * @param {object} params - The parameters for the upgrade request.
	 * @param {string} params.dataId - The unique identifier of the data entity to be upgraded.
	 * @param {string} params.fromLevel - The current security classification level of the data.
	 * @param {string} params.toLevel - The target (higher) security classification level.
	 * @param {string} params.source - Information about the source or reason for the upgrade.
	 * @returns {Promise<{ticketId: string, status: string}>} A promise that resolves with an object containing the ticket ID for tracking the request and its initial status.
	 */
	async requestUpgrade({ dataId, fromLevel, toLevel, source }) {
		this.#stateManager?.emit("cdsEvent", {
			type: "request_upgrade",
			dataId,
			fromLevel,
			toLevel,
			source,
			ts: Date.now(),
		});
		return { ticketId: crypto.randomUUID(), status: "pending" };
	}

	/**
	 * Performs an automated, rule-based downgrade of an entity's data.
	 * It loads an entity, applies sanitization rules, and creates a new, lower-classification
	 * polyinstantiated version of it.
	 * @param {object} params - The parameters for the automated downgrade.
	 * @param {string} params.logicalId - The logical ID of the entity to downgrade.
	 * @param {string} params.toLevel - The target (lower) classification level.
	 * @param {object} params.sanitizerRules - Rules defining how to sanitize the data.
	 * @returns {Promise<{approved: boolean, newEntityId: string}>} The result of the operation.
	 */
	async automatedDowngrade({ logicalId, toLevel, sanitizerRules }) {
		const securityManager = this.#stateManager.managers.securityManager;

		// 1. Load the original, high-classification entity.
		const originalEntity = await this.#stateManager.loadEntity(logicalId);
		if (!originalEntity) {
			throw new Error(`Entity with logicalId ${logicalId} not found.`);
		}

		// 2. Apply sanitization rules to the entity's instance_data.
		const sanitizedData = this.#applySanitization(
			originalEntity.instance_data,
			sanitizerRules
		);

		// 3. Create the new, lower-classification polyinstantiated entity.
		// V8.0 Parity: Simplify the creation of the new instance.
		const newInstance = {
			...originalEntity, // Copy base properties
			logical_id: logicalId,
			classification_level: toLevel,
			instance_data: sanitizedData,
			// The ID will be generated by the storage layer on save.
			id: this.#stateManager.managers.idManager.generate(),
		};

		const newEntityId = await this.#stateManager.saveEntity(newInstance);

		// 4. Log the CDS action for auditing.
		// V8.0 Parity: Correctly attribute the action to the current user.
		await this.#stateManager.recordAuditEvent("CDS_AUTOMATED_DOWNGRADE", {
			logicalId,
			fromLevel: originalEntity.classification_level,
			toLevel,
			rulesApplied: Object.keys(sanitizerRules),
			newEntityId,
			userId: securityManager?.userId,
		});

		return { approved: true, newEntityId };
	}

	/**
	 * Applies sanitization rules to a data object. (Placeholder implementation)
	 * @private
	 */
	#applySanitization(data, rules) {
		// In a real implementation, this would be a complex function that removes, redacts, or transforms fields based on the rules.
		console.log("[CDS] Applying sanitization rules:", rules);
		return { ...data, sanitized_at: new Date().toISOString() };
	}
}
