version: '3.8'
services:
  docker-proxy:
    image: alpine/socat:1.7.4.4-r0
    restart: always
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    ports:
      - "127.0.0.1:2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
